title: "Professional & Personal Blog"
description: "Insights on technology, coding, and life"
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Enables local SCSS overrides
markdown: kramdown
highlighter: rouge

# This tells Jekyll where to find your custom Sass partials
sass:
  sass_dir: _sass
