# _config.yml

# Site settings
title: "Professional & Personal Blog"
description: "Insights on technology, coding, and life"
url: "https://yourdomain.com"      # Replace with your site's URL
baseurl: ""                        # Set to the subpath of your site, e.g., /blog if applicable

theme: minima

# Author Information
author:
  name: "Deniz Akdemir"
  email: "deniz.akdemir.work@gmail.com"
  bio: "Software engineer and tech enthusiast exploring the intersections of coding, technology, and life."
  avatar: "/assets/images/avatar.jpg"  # Optional: Path to your author image

# Defaults for posts and pages
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Deniz Akdemir"
      show_date: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      author: "Deniz Akdemir"

# Navigation configuration for improved user experience
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"

# Plugins to enhance functionality
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown and syntax highlighting settings
markdown: kramdown
kramdown:
  input: GFM                   # Use GitHub Flavored Markdown for extended features
highlighter: rouge

# Sass configuration for custom styles
sass:
  sass_dir: _sass

# Permalink structure for SEO-friendly URLs
permalink: /:categories/:year/:month/:day/:title/

# Optional: Enable pagination for blog posts
paginate: 5
paginate_path: "/page:num/"

# Files and directories to exclude from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Additional SEO settings (overrides defaults if needed)
seo:
  title: "Professional & Personal Blog"
  description: "Insights on technology, coding, and life"
