title: "Professional & Personal Blog"
description: "Insights on technology, coding, and life"
theme: minima

# Author information
author:
  name: Deniz Akdemir
  email: deniz.akdemir.work@gmail.com
# Show author and date information by default
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Deniz Akdemir
      show_date: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Enables local SCSS overrides
markdown: kramdown
highlighter: rouge

# This tells Jekyll where to find your custom Sass partials
sass:
  sass_dir: _sass